=== veditor/veditor/packages/editor/src/lib/format-plugin-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Command format plugin",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "key",
      "command"
    ],
    "properties": {
      "key": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "iconContent": {
        "type": "string"
      },
      "command": {
        "type": "string"
      },
      "commandArg": {
        "type": "string"
      },
      "hotKey": {
        "type": "string"
      }
    }
  }
}

=== veditor/veditor/packages/editor/src/plugins/common/basic-command/basic.json
[
  {
    "key": "bold",
    "icon": "format_bold",
    "hotKey": "mod+b",
    "command": "Bold"
  },
  {
    "key": "italic",
    "icon": "format_italic",
    "hotKey": "mod+i",
    "command": "Italic"
  },
  {
    "key": "underlined",
    "icon": "format_underlined",
    "hotKey": "mod+u",
    "command": "Underline"
  }
]

=== veditor/veditor/packages/editor/src/plugins/common/basic-command/heading.json
[
  {
    "key": "heading-1",
    "iconContent": "H1",
    "command": "formatBlock",
    "commandArg": "H1"
  },
  {
    "key": "heading-2",
    "iconContent": "H2",
    "command": "formatBlock",
    "commandArg": "H2"
  },
  {
    "key": "heading-3",
    "iconContent": "H3",
    "command": "formatBlock",
    "commandArg": "H3"
  },
  {
    "key": "heading-4",
    "iconContent": "H4",
    "command": "formatBlock",
    "commandArg": "H4"
  },
  {
    "key": "heading-5",
    "iconContent": "H5",
    "command": "formatBlock",
    "commandArg": "H5"
  },
  {
    "key": "heading-6",
    "iconContent": "H6",
    "command": "formatBlock",
    "commandArg": "H6"
  }
]
